version: '2'

services:
  nginx:
    image: nginx
    ports:
      - 8086:80
    volumes:
      - ./:/var/www/symfony
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - fpm

  fpm:
    build: docker/php-fpm/
    links:
      - redis
      - mysql
    volumes:
      - ./:/var/www/symfony
      - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini

  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: devdb
      MYSQL_USER: devdb
      MYSQL_PASSWORD: devdb
      MYSQL_ROOT_PASSWORD: 
    volumes:
      - ./docker/mysql/data:/var/lib/mysql

  redis:
    image: redis:latest

  varnish:
    build: docker/varnish/
    links:
      - nginx
    ports:
      - 8087:8087
